### PR TITLE
New version to run on Laravel 9.0 LTS

### PR DESCRIPTION
**Pull request by chrispage1**
Bumped versions to Laravel 9. Removed all instances of older versions from Composer and Travis as this should be uniquely tagged

### CODE REVIEW

**Comment by chrispage1** [comment]
I didn't realise Shift had already done this. But I feel this is a more complete version to be tagged v4+ with no backwards compatible support

**Comment by roy-bongers** [comment]
@petericebear Could you review this PR and create a new release for Laravel 9? This package is currently blocking our upgrade to Laravel 9

**Comment by petericebear** [comment]
Done - v4 is tagged. Sorry for the wait; having covid issues

**Comment by chrispage1** [comment]
@petericebear thank you! Hope all is ok.

Chris.

**Pull request merged**
